# Predictive Anayltics: Support Vector Machines with Regression

Approach for SVM:
– Simply start without a kernel. Then, gradually make your model complex by integrating different
kind of kernels. Also, use grid search to find optimal values for your hyperparameters.
– How good is your model? Evaluate your model’s performance and comment on its shortfalls.
– Show how you model’s performance varies as you increase or decrease temporal or spatial
resolution How does your performance change when you only use census tract as spatial units?
– How could the model be improved further? Explain some of the improvement levers that you might
focus on in a follow-up project.

In [98]:
from run_config import PATHS

In [99]:
baseline_path = PATHS.train_test_dir / "baseline_predictions"

In [100]:
import pandas as pd
import numpy as np
import matplotlib as plt
import datetime
from joblib import load, dump
import h3
from tabulate import tabulate

import pandas as pd
import numpy as np
#import matplotlib as plt
import datetime

from sklearn.kernel_approximation import Nystroem
from joblib import load, dump
import h3
from joblib import Memory
import jinja2

In [101]:
INPUT =  f"../models/svm/"

In [102]:
def met(own_results, baseline):
    score = 1 - (own_results/baseline)
    return score

### load y_pred and models

In [103]:
SPATIAL_UNITS = ["HEXAGON_7", "HEXAGON_8", "CENSUS_TRACTS", "COMMUNITY_AREAS"]
TIME_UNITS = ["1H", "4H", "24H"]

In [104]:
path_csv = {
    (spatial, time): f"{INPUT}result_{spatial}_{time}.csv"
    for spatial in SPATIAL_UNITS
    for time in TIME_UNITS
}

In [105]:
results = {
    (spatial, time): pd.read_csv(path)
    for (spatial, time), path in path_csv.items()
}

In [106]:
combined = pd.concat(
    [df.assign(spatial=spatial, time=time) for (spatial, time), df in results.items()],
    ignore_index=True
)
combined.to_csv("../results/results_svr.csv", index=False)

In [ ]:
# table 
results_df = combined[["spatial", "time", "MAE", "MSE", "RMSE", "R2 Score"]]
results_df = results_df.sort_values(["spatial", "time"]).reset_index(drop=True)

styled = results_df.style.format({
    "MAE": "{:.2f}",-
    "MSE": "{:.2f}",
    "RMSE": "{:.2f}",
    "R2 Score": "{:.3f}",
}).background_gradient(subset=["R2 Score"], cmap="RdYlGn", vmin=0, vmax=1) \
  .background_gradient(subset=["MAE", "RMSE", "MSE"], cmap="RdYlGn_r") \
  .set_caption("SVM Regression Results by Spatial Unit and Time Granularity")

styled

In [108]:
path_y_pred = {
    (spatial, time): f"{INPUT}model_{spatial}_{time}.csv"
    for spatial in SPATIAL_UNITS
    for time in TIME_UNITS
}

In [109]:
models = {
    (spatial, time): pd.read_csv(path)
    for (spatial, time), path in path_y_pred.items()
}

In [110]:
models

{('HEXAGON_7',
  '1H'):           y_pred  y_test          h3_cell                 date
 0       1.947378       0  872664c8effffff  2026-01-13 01:00:00
 1       0.995485       0  872664c8effffff  2025-11-30 01:00:00
 2       0.000000       0  872664c13ffffff  2025-07-31 14:00:00
 3       0.000000       0  872664c8effffff  2025-07-31 14:00:00
 4       0.000000       0  872664c8effffff  2025-06-29 06:00:00
 ...          ...     ...              ...                  ...
 285571  0.565287       0  872664d9effffff  2025-06-01 23:00:00
 285572  0.000000       0  872664d9effffff  2025-08-13 22:00:00
 285573  1.055305       0  872664d9effffff  2025-07-14 06:00:00
 285574  2.518632       0  872664d9effffff  2025-01-11 06:00:00
 285575  0.000000       0  872664d9effffff  2025-01-11 15:00:00

 [285576 rows x 4 columns],
 ('HEXAGON_7',
  '4H'):            y_pred  y_test          h3_cell                 date
 0        0.000000       0  872664c8cffffff  2025-08-12 20:00:00
 1        3.821714       0  872759341ffffff  2025-08-12 16:00:00
 2        0.000000       0  872664ca5ffffff  2025-08-12 08:00:00
 3        4.216059       0  872664561ffffff  2025-08-12 04:00:00
 4        6.882722      21  872664ca9ffffff  2025-08-12 12:00:00
 ...           ...     ...              ...                  ...
 71389   18.786606       2  872664525ffffff  2025-03-11 12:00:00
 71390  852.410214     753  872664c1effffff  2025-07-12 12:00:00
 71391    0.000000       0  872664d8affffff  2025-07-12 20:00:00
 71392    0.000000       0  872664ca0ffffff  2025-03-11 16:00:00
 71393    0.000000       0  87275934cffffff  2025-03-11 12:00:00

 [71394 rows x 4 columns],
 ('HEXAGON_7',
  '24H'):           y_pred  y_test          h3_cell        date
 0       8.252361       0  872664cc8ffffff  2025-07-10
 1      53.397013       0  872664cc8ffffff  2026-04-16
 2      23.801483       0  872664ca6ffffff  2025-09-27
 3      12.123205       4  872664ce3ffffff  2025-09-27
 4       7.465442       0  872664560ffffff  2025-01-15
 ...          ...     ...              ...         ...
 11894   0.000000       0  87275934affffff  2026-01-13
 11895  13.314318       0  872664c32ffffff  2026-01-13
 11896  23.318881       0  872664ca6ffffff  2025-07-01
 11897   3.173920       0  87275934affffff  2025-07-01
 11898   0.000000       0  872664cb6ffffff  2025-09-07

 [11899 rows x 4 columns],
 ('HEXAGON_8',
  '1H'):            y_pred  y_test          h3_cell                 date
 0        0.000000       0  882664cc3dfffff  2025-11-14 14:00:00
 1        0.133656       0  882664cc3dfffff  2025-11-14 11:00:00
 2        0.000000       0  882664cc3dfffff  2025-11-14 16:00:00
 3        0.000000       0  882664cce9fffff  2025-09-27 05:00:00
 4        0.308934       0  88275934d1fffff  2025-11-14 16:00:00
 ...           ...     ...              ...                  ...
 1709947  0.103628       0  882664c805fffff  2025-02-27 18:00:00
 1709948  0.061351       0  882664525dfffff  2025-03-10 07:00:00
 1709949  0.320756       0  882664525dfffff  2025-01-11 23:00:00
 1709950  0.037936       0  882664caa3fffff  2025-06-23 19:00:00
 1709951  0.000000       0  882664caa3fffff  2025-01-11 12:00:00

 [1709952 rows x 4 columns],
 ('HEXAGON_8',
  '4H'):           y_pred  y_test          h3_cell                 date
 0       0.000000       0  882664cc81fffff  2025-02-27 04:00:00
 1       0.000000       0  882664ccb9fffff  2025-02-27 04:00:00
 2       0.000000       0  882664ca6dfffff  2025-12-14 20:00:00
 3       1.130007       0  88275935cbfffff  2025-12-14 20:00:00
 4       0.000000       0  882664ca89fffff  2025-02-27 20:00:00
 ...          ...     ...              ...                  ...
 427483  0.000000       0  8826645759fffff  2026-02-13 00:00:00
 427484  0.000000       0  882664cae1fffff  2026-02-13 04:00:00
 427485  0.996080       0  882664cb39fffff  2025-06-27 20:00:00
 427486  0.000000       0  882664c80dfffff  2025-06-29 00:00:00
 427487  0.000000       0  882664c80dfffff  2025-06-29 16:00:00

 [427488 rows x 4 columns],
 ('HEXAGON_8',
  '24H'):            y_pred  y_test          h3_cell        date
 0        0.000000      16  882664c137fffff  2025-11-21
 1        0.000000       0  882664cd63fffff  2025-11-21
 2      226.942900     271  882664c1edfffff  2025-11-21
 3        0.000000       0  882664525dfffff  2025-03-11
 4        0.000000       0  8826645623fffff  2025-03-11
 ...           ...     ...              ...         ...
 71243    8.294622       0  882664ca21fffff  2025-11-30
 71244   13.529600       0  882759340bfffff  2025-11-30
 71245    3.790468       0  882664c109fffff  2025-11-30
 71246    6.969581       0  882664c885fffff  2025-11-30
 71247    5.366450       0  882664cdcdfffff  2025-11-30

 [71248 rows x 4 columns],
 ('CENSUS_TRACTS',
  '1H'):            y_pred  y_test  census_tract                 date
 0        0.165808       0   17031243100  2025-11-05 20:00:00
 1        0.066763       0   17031351500  2025-09-22 10:00:00
 2        0.111647       0   17031351100  2026-03-24 17:00:00
 3        0.418540       0   17031031600  2025-08-30 19:00:00
 4        0.000000       0   17031031600  2026-03-24 17:00:00
 ...           ...     ...           ...                  ...
 1538251  0.184153       0   17031060200  2026-01-13 06:00:00
 1538252  0.000000       0   17031611500  2026-01-13 09:00:00
 1538253  0.000000       0   17031060200  2025-03-21 18:00:00
 1538254  0.000000       0   17031020600  2026-01-13 00:00:00
 1538255  0.000000       0   17031611500  2025-03-21 16:00:00

 [1538256 rows x 4 columns],
 ('CENSUS_TRACTS',
  '4H'):           y_pred  y_test  census_tract                 date
 0       0.107657       0   17031200600  2025-12-25 04:00:00
 1       1.327935       0   17031410800  2025-07-10 04:00:00
 2       0.375668       0   17031691500  2025-07-10 08:00:00
 3       0.132974       0   17031450300  2025-07-10 08:00:00
 4       0.000000       0   17031450300  2025-12-25 08:00:00
 ...          ...     ...           ...                  ...
 384559  0.000000       0   17031700500  2025-06-27 16:00:00
 384560  1.991285       0   17031550100  2025-01-14 12:00:00
 384561  1.507934       0   17031550100  2025-01-14 20:00:00
 384562  1.812057       0   17031550100  2025-01-14 00:00:00
 384563  3.349771       0   17031032000  2025-01-14 04:00:00

 [384564 rows x 4 columns],
 ('CENSUS_TRACTS',
  '24H'):          y_pred  y_test  census_tract        date
 0      6.254862       0   17031071600  2026-04-26
 1      9.323391       0   17031411400  2026-04-26
 2      6.288717       0   17031601100  2026-04-26
 3      0.000000       0   17031810501  2025-12-14
 4      0.000000       0   17031190200  2025-09-11
 ...         ...     ...           ...         ...
 64089  3.817315       0   17031283400  2025-01-15
 64090  4.989375       0   17031530100  2025-01-15
 64091  3.531277       0   17031150700  2025-01-15
 64092  0.000000       0   17031220600  2025-07-31
 64093  0.000000       0   17031260600  2025-07-31

 [64094 rows x 4 columns],
 ('COMMUNITY_AREAS',
  '1H'):            y_pred  y_test  community_area                 date
 0        0.000000       0              48  2025-11-14 22:00:00
 1        0.000000       0              50  2025-11-14 22:00:00
 2        0.020311       0              50  2026-03-11 09:00:00
 3        0.000000       0              46  2025-07-10 09:00:00
 4        0.000000       0              48  2025-08-24 11:00:00
 ...           ...     ...             ...                  ...
 134899   6.820826       0               7  2025-12-25 16:00:00
 134900   1.084135       0              10  2025-12-25 23:00:00
 134901  61.055595       4               8  2025-12-25 21:00:00
 134902   2.247537       0               8  2025-08-12 01:00:00
 134903   5.188279       5               7  2025-08-12 07:00:00

 [134904 rows x 4 columns],
 ('COMMUNITY_AREAS',
  '4H'):           y_pred  y_test  community_area                 date
 0      18.370013       0              36  2025-03-11 08:00:00
 1       0.053894       0              36  2025-08-12 04:00:00
 2       9.694248       1              36  2025-06-20 12:00:00
 3       0.000000       0              39  2025-06-20 20:00:00
 4      11.565620       0              36  2025-05-15 12:00:00
 ...          ...     ...             ...                  ...
 33721   0.000000       0               2  2025-07-14 08:00:00
 33722   0.000000       0               5  2025-07-14 00:00:00
 33723   0.000000       0               4  2025-07-01 00:00:00
 33724   2.738058       1               3  2025-01-14 16:00:00
 33725   2.871822       0               1  2025-07-01 08:00:00

 [33726 rows x 4 columns],
 ('COMMUNITY_AREAS',
  '24H'):            y_pred  y_test  community_area        date
 0      729.428671     502              76  2026-02-07
 1     1162.064267    2403              76  2025-05-15
 2        0.000000       1              77  2026-02-07
 3     1173.010401    1445              76  2025-11-14
 4        4.879027       1              77  2026-02-13
 ...           ...     ...             ...         ...
 5616     0.000000       0              46  2025-09-07
 5617     0.000000       0              46  2025-12-14
 5618    22.871664       0              60  2025-09-03
 5619    89.388369     141              56  2025-01-15
 5620     5.928413       0              57  2025-09-07

 [5621 rows x 4 columns]}

In [111]:
baseline = pd.read_parquet(f"{baseline_path}/baseline_test_metrics.parquet")

In [112]:
baseline

,dataset,baseline,metric,value
0,hexagon_h3r7_1h,zero,n_samples,285576.000000
1,hexagon_h3r7_1h,zero,mae,1.936539
2,hexagon_h3r7_1h,zero,mse,299.480387
3,hexagon_h3r7_1h,zero,rmse,17.305502
4,hexagon_h3r7_1h,zero,r2,-0.012681
...,...,...,...,...
571,community_areas_unfiltered_4h,spatial_time_weekday_mean,nonzero_rmse,38.622753
572,community_areas_unfiltered_4h,spatial_time_weekday_mean,peak_threshold,63.000000
573,community_areas_unfiltered_4h,spatial_time_weekday_mean,peak_share,0.081065
574,community_areas_unfiltered_4h,spatial_time_weekday_mean,peak_mae,66.392831
575,community_areas_unfiltered_4h,spatial_time_weekday_mean,peak_rmse,119.726233

In [135]:
results_df["spatial_clean"] = (
    results_df["spatial"].str.lower()
    .str.replace("hexagon_", "hexagon_h3r", regex=False)  # HEXAGON_7 -> hexagon_h3r7
)
results_df["time_clean"] = results_df["time"].str.lower()  # 1H -> 1h
results_df["run"] = results_df["spatial_clean"] + "_" + results_df["time_clean"]

own_results = results_df.melt(
    id_vars=["dataset"],
    value_vars=["MAE", "MSE", "RMSE", "R2 Score"],
    var_name="metric",
    value_name="value",
)

own_results["metric"] = own_results["metric"].str.lower().str.replace(" score", "", regex=False)

In [138]:
baseline_mae = baseline[baseline["metric"] == "mae"][["dataset", "metric", "value"]]
own_mae = own_results[own_results["metric"] == "mae"][["dataset", "metric", "value"]]

In [139]:

merged = own_mae.merge(
    baseline_mae,
    on="dataset",
    suffixes=("_own", "_baseline")
)
merged

                dataset metric_own  value_own metric_baseline  value_baseline
0      census_tracts_1h        mae   0.359323             mae        0.359517
1      census_tracts_1h        mae   0.359323             mae        0.359517
2      census_tracts_1h        mae   0.359323             mae        0.135651
3     census_tracts_24h        mae  10.595766             mae        8.628405
4     census_tracts_24h        mae  10.595766             mae        8.628405
5     census_tracts_24h        mae  10.595766             mae        2.175618
6      census_tracts_4h        mae   1.349104             mae        1.438068
7      census_tracts_4h        mae   1.349104             mae        1.438068
8      census_tracts_4h        mae   1.349104             mae        0.439747
9    community_areas_1h        mae   2.378622             mae        4.099426
10   community_areas_1h        mae   2.378622             mae        4.099426
11   community_areas_1h        mae   2.378622             mae        1.216447
12  community_areas_24h        mae  44.688618             mae       98.386230
13  community_areas_24h        mae  44.688618             mae       98.386230
14  community_areas_24h        mae  44.688618             mae       21.985000
15   community_areas_4h        mae   8.464290             mae       16.397705
16   community_areas_4h        mae   8.464290             mae       16.397705
17   community_areas_4h        mae   8.464290             mae        4.247144
18      hexagon_h3r7_1h        mae   1.634766             mae        1.936539
19      hexagon_h3r7_1h        mae   1.634766             mae        1.936539
20      hexagon_h3r7_1h        mae   1.634766             mae        0.592475
21     hexagon_h3r7_24h        mae  26.099628             mae       46.476931
22     hexagon_h3r7_24h        mae  26.099628             mae       46.476931
23     hexagon_h3r7_24h        mae  26.099628             mae       10.443267
24      hexagon_h3r7_4h        mae   5.527029             mae        7.746155
25      hexagon_h3r7_4h        mae   5.527029             mae        7.746155
26      hexagon_h3r7_4h        mae   5.527029             mae        2.045525

In [142]:
merged["score"] = met(merged["metric_own"], merged["metric_baseline"])

TypeError: unsupported operand type(s) for /: 'str' and 'str'